### ISSUE TITLE
Insufficient buffer capacity for event channel

### ISSUE THREAD

**Issue by stijnb-Ideal** [GenesysPureEngage/workspace-client-java#25]
Following item can be reproduced when running the below block, on both JDK8/JDK11.
 WorkspaceApi workspaceApi = new WorkspaceApi(API_KEY, API_WORK_URL);
 User user = workspaceApi.initialize(accessToken);

It looks like the event channel is not opening (error about buffer capacity visible)

`DirectByteBufferR@31494137[p=10,l=16384,c=16384,r=16374]={00006000\r\n<<<e}]},{"name":"Cal...24819","id":339>>>}
2021-07-15 09:58:50:974 +0200 [HttpClient@6f3b5d16-18] DEBUG org.eclipse.jetty.client.HttpExchange - Failed HttpExchange@a4c403c req=TERMINATED/null@null res=COMPLETED/java.lang.IllegalArgumentException: Buffering capacity 1048576 exceeded@384ce2db: req=false/rsp=true {}
java.lang.IllegalArgumentException: Buffering capacity 1048576 exceeded
	at org.eclipse.jetty.client.util.BufferingResponseListener.onContent(BufferingResponseListener.java:124)
	at org.eclipse.jetty.client.api.Response$Listener$Adapter.onContent(Response.java:248)
	at org.eclipse.jetty.client.ResponseNotifier.notifyContent(ResponseNotifier.java:133)
	at org.eclipse.jetty.client.ResponseNotifier.notifyContent(ResponseNotifier.java:125)
	at org.eclipse.jetty.client.HttpReceiver.responseContent(HttpReceiver.java:337)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.content(HttpReceiverOverHTTP.java:283)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1787)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by stijnbrebels** [comment]
@huideng-telus 
we implemented a hack/workaround in the java library, by raising the buffer size.

It seems that the 'configuration' returned when initializing workspace API is too large, throwing an exception.

Check ClientTransport.java, in the constructor currently an empty hashmap is passed to LongPollingTransport.java
In the map you can push the key 'maxMessageSize' with a buffer size value (we tried 104867600)
